<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <NoWarn>$(NoWarn);CS1701;CS1702</NoWarn>
  </PropertyGroup>
</Project>
